<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Homework8: Basic Modeling Practice</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body>

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#eda-checking-the-data" id="toc-eda-checking-the-data" class="nav-link active" data-scroll-target="#eda-checking-the-data">EDA : Checking the data</a></li>
  <li><a href="#split-the-data" id="toc-split-the-data" class="nav-link" data-scroll-target="#split-the-data">Split the Data</a></li>
  <li><a href="#fitting-mlr-models" id="toc-fitting-mlr-models" class="nav-link" data-scroll-target="#fitting-mlr-models">Fitting MLR Models</a>
  <ul class="collapse">
  <li><a href="#first-recipe" id="toc-first-recipe" class="nav-link" data-scroll-target="#first-recipe">First recipe</a></li>
  <li><a href="#second-recipe" id="toc-second-recipe" class="nav-link" data-scroll-target="#second-recipe">Second recipe</a></li>
  <li><a href="#third-recipe" id="toc-third-recipe" class="nav-link" data-scroll-target="#third-recipe">Third recipe</a></li>
  <li><a href="#set-up-lm" id="toc-set-up-lm" class="nav-link" data-scroll-target="#set-up-lm">Set up LM</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework8: Basic Modeling Practice</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>#Load libraries</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>#Read the dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1.1 Use readr's encoding to detect on the raw file</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>raw_bytes <span class="ot">&lt;-</span> <span class="fu">read_file_raw</span>(<span class="st">"https://www4.stat.ncsu.edu/~online/datasets/SeoulBikeData.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">guess_encoding</span>(raw_bytes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  encoding   confidence
  &lt;chr&gt;           &lt;dbl&gt;
1 ISO-8859-1       0.51
2 ISO-8859-2       0.26</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1.2 Read the dataset</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>Bike_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"https://www4.stat.ncsu.edu/~online/datasets/SeoulBikeData.csv"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">locale =</span> <span class="fu">locale</span>(<span class="at">encoding =</span> <span class="st">"ISO-8859-1"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 8760 Columns: 14
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): Date, Seasons, Holiday, Functioning Day
dbl (10): Rented Bike Count, Hour, Temperature(°C), Humidity(%), Wind speed ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Bike_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8,760 × 14
   Date       `Rented Bike Count`  Hour `Temperature(°C)` `Humidity(%)`
   &lt;chr&gt;                    &lt;dbl&gt; &lt;dbl&gt;             &lt;dbl&gt;         &lt;dbl&gt;
 1 01/12/2017                 254     0              -5.2            37
 2 01/12/2017                 204     1              -5.5            38
 3 01/12/2017                 173     2              -6              39
 4 01/12/2017                 107     3              -6.2            40
 5 01/12/2017                  78     4              -6              36
 6 01/12/2017                 100     5              -6.4            37
 7 01/12/2017                 181     6              -6.6            35
 8 01/12/2017                 460     7              -7.4            38
 9 01/12/2017                 930     8              -7.6            37
10 01/12/2017                 490     9              -6.5            27
# ℹ 8,750 more rows
# ℹ 9 more variables: `Wind speed (m/s)` &lt;dbl&gt;, `Visibility (10m)` &lt;dbl&gt;,
#   `Dew point temperature(°C)` &lt;dbl&gt;, `Solar Radiation (MJ/m2)` &lt;dbl&gt;,
#   `Rainfall(mm)` &lt;dbl&gt;, `Snowfall (cm)` &lt;dbl&gt;, Seasons &lt;chr&gt;, Holiday &lt;chr&gt;,
#   `Functioning Day` &lt;chr&gt;</code></pre>
</div>
</div>
<section id="eda-checking-the-data" class="level1">
<h1>EDA : Checking the data</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2 Check for missingness</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>Bike_data <span class="sc">|&gt;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)))) <span class="sc">|&gt;</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"Variable"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"missing_count"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(missing_count))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 2
   Variable                  missing_count
   &lt;chr&gt;                             &lt;int&gt;
 1 Date                                  0
 2 Rented Bike Count                     0
 3 Hour                                  0
 4 Temperature(°C)                       0
 5 Humidity(%)                           0
 6 Wind speed (m/s)                      0
 7 Visibility (10m)                      0
 8 Dew point temperature(°C)             0
 9 Solar Radiation (MJ/m2)               0
10 Rainfall(mm)                          0
11 Snowfall (cm)                         0
12 Seasons                               0
13 Holiday                               0
14 Functioning Day                       0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2.1 Check the column types and the values within the columns</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Bike_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [8,760 × 14] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Date                     : chr [1:8760] "01/12/2017" "01/12/2017" "01/12/2017" "01/12/2017" ...
 $ Rented Bike Count        : num [1:8760] 254 204 173 107 78 100 181 460 930 490 ...
 $ Hour                     : num [1:8760] 0 1 2 3 4 5 6 7 8 9 ...
 $ Temperature(°C)          : num [1:8760] -5.2 -5.5 -6 -6.2 -6 -6.4 -6.6 -7.4 -7.6 -6.5 ...
 $ Humidity(%)              : num [1:8760] 37 38 39 40 36 37 35 38 37 27 ...
 $ Wind speed (m/s)         : num [1:8760] 2.2 0.8 1 0.9 2.3 1.5 1.3 0.9 1.1 0.5 ...
 $ Visibility (10m)         : num [1:8760] 2000 2000 2000 2000 2000 ...
 $ Dew point temperature(°C): num [1:8760] -17.6 -17.6 -17.7 -17.6 -18.6 -18.7 -19.5 -19.3 -19.8 -22.4 ...
 $ Solar Radiation (MJ/m2)  : num [1:8760] 0 0 0 0 0 0 0 0 0.01 0.23 ...
 $ Rainfall(mm)             : num [1:8760] 0 0 0 0 0 0 0 0 0 0 ...
 $ Snowfall (cm)            : num [1:8760] 0 0 0 0 0 0 0 0 0 0 ...
 $ Seasons                  : chr [1:8760] "Winter" "Winter" "Winter" "Winter" ...
 $ Holiday                  : chr [1:8760] "No Holiday" "No Holiday" "No Holiday" "No Holiday" ...
 $ Functioning Day          : chr [1:8760] "Yes" "Yes" "Yes" "Yes" ...
 - attr(*, "spec")=
  .. cols(
  ..   Date = col_character(),
  ..   `Rented Bike Count` = col_double(),
  ..   Hour = col_double(),
  ..   `Temperature(°C)` = col_double(),
  ..   `Humidity(%)` = col_double(),
  ..   `Wind speed (m/s)` = col_double(),
  ..   `Visibility (10m)` = col_double(),
  ..   `Dew point temperature(°C)` = col_double(),
  ..   `Solar Radiation (MJ/m2)` = col_double(),
  ..   `Rainfall(mm)` = col_double(),
  ..   `Snowfall (cm)` = col_double(),
  ..   Seasons = col_character(),
  ..   Holiday = col_character(),
  ..   `Functioning Day` = col_character()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p>we have 8,760 rows of data and 14 columns. of the 14 variables,4 are character including date variable which needs to be changed to date type later.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2.2 basic summary statistics for the numeric variables</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Select only numeric columns</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>numeric_data <span class="ot">&lt;-</span> Bike_data <span class="sc">|&gt;</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric))</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(numeric_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          vars    n    mean     sd  median trimmed    mad   min
Rented Bike Count            1 8760  704.60 645.00  504.50  612.58 553.75   0.0
Hour                         2 8760   11.50   6.92   11.50   11.50   8.90   0.0
Temperature(°C)              3 8760   12.88  11.94   13.70   13.19  13.94 -17.8
Humidity(%)                  4 8760   58.23  20.36   57.00   58.02  23.72   0.0
Wind speed (m/s)             5 8760    1.72   1.04    1.50    1.63   1.04   0.0
Visibility (10m)             6 8760 1436.83 608.30 1698.00 1509.50 447.75  27.0
Dew point temperature(°C)    7 8760    4.07  13.06    5.10    4.76  14.38 -30.6
Solar Radiation (MJ/m2)      8 8760    0.57   0.87    0.01    0.38   0.01   0.0
Rainfall(mm)                 9 8760    0.15   1.13    0.00    0.00   0.00   0.0
Snowfall (cm)               10 8760    0.08   0.44    0.00    0.00   0.00   0.0
                              max   range  skew kurtosis   se
Rented Bike Count         3556.00 3556.00  1.15     0.85 6.89
Hour                        23.00   23.00  0.00    -1.20 0.07
Temperature(°C)             39.40   57.20 -0.20    -0.84 0.13
Humidity(%)                 98.00   98.00  0.06    -0.80 0.22
Wind speed (m/s)             7.40    7.40  0.89     0.73 0.01
Visibility (10m)          2000.00 1973.00 -0.70    -0.96 6.50
Dew point temperature(°C)   27.20   57.80 -0.37    -0.76 0.14
Solar Radiation (MJ/m2)      3.52    3.52  1.50     1.12 0.01
Rainfall(mm)                35.00   35.00 14.53   284.76 0.01
Snowfall (cm)                8.80    8.80  8.44    93.73 0.00</code></pre>
</div>
</div>
<p>We used describe function from psych package to came up with the summary table for the numeric variables. we have 10 numeric variables and according to the data, the average bike rental count computed across all hours and dates were 704.6.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2.3 check the unique values for the categorical variables</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>unique_cats <span class="ot">&lt;-</span> Bike_data <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(<span class="sc">~</span> (<span class="fu">is.character</span>(.) <span class="sc">|</span> <span class="fu">is.factor</span>(.)))) <span class="sc">|&gt;</span>     <span class="co"># only categorical</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">matches</span>(<span class="st">"Date"</span>, <span class="at">ignore.case =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span>          <span class="co"># drop date column </span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(unique)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a> unique_cats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Seasons
[1] "Winter" "Spring" "Summer" "Autumn"

$Holiday
[1] "No Holiday" "Holiday"   

$`Functioning Day`
[1] "Yes" "No" </code></pre>
</div>
</div>
<p>we have three categorical variables with the above unique values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. change character date to date format</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>Bike_data<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">dmy</span>(Bike_data<span class="sc">$</span>Date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 4.turn Seasons, Holiday, and Functioning Day to factor</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>Bike_data <span class="ot">&lt;-</span> Bike_data <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Seasons =</span> <span class="fu">as.factor</span>(Seasons))<span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Holiday =</span> <span class="fu">as.factor</span>(Holiday)) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Functioning Day</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">as.factor</span>(<span class="st">`</span><span class="at">Functioning Day</span><span class="st">`</span>))</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>Bike_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8,760 × 14
   Date       `Rented Bike Count`  Hour `Temperature(°C)` `Humidity(%)`
   &lt;date&gt;                   &lt;dbl&gt; &lt;dbl&gt;             &lt;dbl&gt;         &lt;dbl&gt;
 1 2017-12-01                 254     0              -5.2            37
 2 2017-12-01                 204     1              -5.5            38
 3 2017-12-01                 173     2              -6              39
 4 2017-12-01                 107     3              -6.2            40
 5 2017-12-01                  78     4              -6              36
 6 2017-12-01                 100     5              -6.4            37
 7 2017-12-01                 181     6              -6.6            35
 8 2017-12-01                 460     7              -7.4            38
 9 2017-12-01                 930     8              -7.6            37
10 2017-12-01                 490     9              -6.5            27
# ℹ 8,750 more rows
# ℹ 9 more variables: `Wind speed (m/s)` &lt;dbl&gt;, `Visibility (10m)` &lt;dbl&gt;,
#   `Dew point temperature(°C)` &lt;dbl&gt;, `Solar Radiation (MJ/m2)` &lt;dbl&gt;,
#   `Rainfall(mm)` &lt;dbl&gt;, `Snowfall (cm)` &lt;dbl&gt;, Seasons &lt;fct&gt;, Holiday &lt;fct&gt;,
#   `Functioning Day` &lt;fct&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. give a cleaner variable names, strip the units from the variables that have units at the end to make it easy to use.</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>Bike_data <span class="ot">&lt;-</span> Bike_data <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>(<span class="at">case =</span> <span class="st">"snake"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(<span class="sc">~</span> <span class="fu">str_remove_all</span>(., <span class="st">"_?(c|%|m_s|mj_m2|10m|cm|mm|min|m|percent)$"</span>))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>Bike_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8,760 × 14
   date       rented_bike_count  hour temperature humidity wind_speed visibility
   &lt;date&gt;                 &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
 1 2017-12-01               254     0        -5.2       37        2.2       2000
 2 2017-12-01               204     1        -5.5       38        0.8       2000
 3 2017-12-01               173     2        -6         39        1         2000
 4 2017-12-01               107     3        -6.2       40        0.9       2000
 5 2017-12-01                78     4        -6         36        2.3       2000
 6 2017-12-01               100     5        -6.4       37        1.5       2000
 7 2017-12-01               181     6        -6.6       35        1.3       2000
 8 2017-12-01               460     7        -7.4       38        0.9       2000
 9 2017-12-01               930     8        -7.6       37        1.1       2000
10 2017-12-01               490     9        -6.5       27        0.5       1928
# ℹ 8,750 more rows
# ℹ 7 more variables: dew_point_temperature &lt;dbl&gt;, solar_radiation &lt;dbl&gt;,
#   rainfall &lt;dbl&gt;, snowfall &lt;dbl&gt;, seasons &lt;fct&gt;, holiday &lt;fct&gt;,
#   functioning_day &lt;fct&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 6.Create summary statistics (especially related to the bike rental counts)</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co">#do counts across your categorical variables</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a> Bike_data<span class="sc">|&gt;</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
      n  mean median    sd   min   max
  &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  8760  705.   504.  645.     0  3556</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Bike_data<span class="sc">$</span>rented_bike_count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    0.0   191.0   504.5   704.6  1065.2  3556.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Bike_data<span class="sc">$</span>rented_bike_count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework8_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>created summary statistics related to bike rental count across categorical variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bike rental by Season</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>season_summary <span class="ot">&lt;-</span> Bike_data <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(seasons) <span class="sc">|&gt;</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_count =</span> <span class="fu">mean</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_count =</span> <span class="fu">median</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_count =</span> <span class="fu">sd</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>season_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  seasons mean_count median_count sd_count     n
  &lt;fct&gt;        &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
1 Autumn        820.         764.     651.  2184
2 Spring        730.         583      622.  2208
3 Summer       1034.         906.     690.  2208
4 Winter        226.         203      150.  2160</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bike rental by Holiday</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>holiday_summary <span class="ot">&lt;-</span> Bike_data <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(holiday) <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_count =</span> <span class="fu">mean</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_count =</span> <span class="fu">median</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_count =</span> <span class="fu">sd</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>holiday_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  holiday    mean_count median_count sd_count     n
  &lt;fct&gt;           &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
1 Holiday          500.         240      571.   432
2 No Holiday       715.         524.     647.  8328</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bike rental by functioning day</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>func_summary <span class="ot">&lt;-</span> Bike_data <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(functioning_day) <span class="sc">|&gt;</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_count =</span> <span class="fu">mean</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_count =</span> <span class="fu">median</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_count =</span> <span class="fu">sd</span>(rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>func_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  functioning_day mean_count median_count sd_count     n
  &lt;fct&gt;                &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
1 No                      0             0       0    295
2 Yes                   729.          542     642.  8465</code></pre>
</div>
</div>
<p>Based on the summary output, we can see that the average number of bike rental was the highest during summer season.Also, it indicates that bike rental is generally higher on regular days compared to holidays. we should note that the bike rental count is 0 where the functioning_day is “No” which means the stations were closed on non-functioning days, thus it makes sense to subset the data to ONLY functioning days before further analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#sub-setting the data for functioning_day == "Yes" </span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>Bike_data2 <span class="ot">&lt;-</span> Bike_data<span class="sc">|&gt;</span><span class="fu">filter</span>(functioning_day <span class="sc">==</span> <span class="st">"Yes"</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>Bike_data2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8,465 × 14
   date       rented_bike_count  hour temperature humidity wind_speed visibility
   &lt;date&gt;                 &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
 1 2017-12-01               254     0        -5.2       37        2.2       2000
 2 2017-12-01               204     1        -5.5       38        0.8       2000
 3 2017-12-01               173     2        -6         39        1         2000
 4 2017-12-01               107     3        -6.2       40        0.9       2000
 5 2017-12-01                78     4        -6         36        2.3       2000
 6 2017-12-01               100     5        -6.4       37        1.5       2000
 7 2017-12-01               181     6        -6.6       35        1.3       2000
 8 2017-12-01               460     7        -7.4       38        0.9       2000
 9 2017-12-01               930     8        -7.6       37        1.1       2000
10 2017-12-01               490     9        -6.5       27        0.5       1928
# ℹ 8,455 more rows
# ℹ 7 more variables: dew_point_temperature &lt;dbl&gt;, solar_radiation &lt;dbl&gt;,
#   rainfall &lt;dbl&gt;, snowfall &lt;dbl&gt;, seasons &lt;fct&gt;, holiday &lt;fct&gt;,
#   functioning_day &lt;fct&gt;</code></pre>
</div>
</div>
<p>Once we filtered our data for only the functioning days, We summarized our data across hours so that each day has one observation. To do this, we grouped our data by date,season and holiday variable and summarized across bike count, rainfall and snowfall to get the their total and summarized across weather related variables to get their mean value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 7.To simplify our analysis, we’ll summarize across the hours so that each day has one observation associated with it.</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>sumry <span class="ot">&lt;-</span> Bike_data2 <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(date,seasons, holiday ) <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">c</span>(rented_bike_count, rainfall, snowfall), <span class="sc">~</span> <span class="fu">sum</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.names =</span> <span class="st">"tot_{.col}"</span>) ,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">c</span>(temperature,humidity,wind_speed,visibility,dew_point_temperature,solar_radiation),</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>           <span class="sc">~</span> <span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.names =</span> <span class="st">"mean_{.col}"</span> ),</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>)<span class="sc">%&gt;%</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'date', 'seasons'. You can override using
the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>sumry</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 353 × 12
   date       seasons holiday    tot_rented_bike_count tot_rainfall tot_snowfall
   &lt;date&gt;     &lt;fct&gt;   &lt;fct&gt;                      &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;
 1 2017-12-01 Winter  No Holiday                  9539          0            0  
 2 2017-12-02 Winter  No Holiday                  8523          0            0  
 3 2017-12-03 Winter  No Holiday                  7222          4            0  
 4 2017-12-04 Winter  No Holiday                  8729          0.1          0  
 5 2017-12-05 Winter  No Holiday                  8307          0            0  
 6 2017-12-06 Winter  No Holiday                  6669          1.3          8.6
 7 2017-12-07 Winter  No Holiday                  8549          0           10.4
 8 2017-12-08 Winter  No Holiday                  8032          0            0  
 9 2017-12-09 Winter  No Holiday                  7233          0            0  
10 2017-12-10 Winter  No Holiday                  3453          4.1         32.5
# ℹ 343 more rows
# ℹ 6 more variables: mean_temperature &lt;dbl&gt;, mean_humidity &lt;dbl&gt;,
#   mean_wind_speed &lt;dbl&gt;, mean_visibility &lt;dbl&gt;,
#   mean_dew_point_temperature &lt;dbl&gt;, mean_solar_radiation &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Number of days</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(sumry)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 353</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#confirm no duplicates</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">duplicated</span>(sumry[, <span class="fu">c</span>(<span class="st">"date"</span>, <span class="st">"seasons"</span>, <span class="st">"holiday"</span>)]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>We can see that we have 353 distinct rows per day and no duplicates were found.</p>
<p>once “sumry” is my clean, analysis-ready dataset,we recreated the basic summary stats.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 8. Recreate your basic summary stats and then create some plots to explore relationships. Report correlation between your numeric variables as well.</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Bike rental by Season</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>season_summaryNew <span class="ot">&lt;-</span> sumry <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(seasons) <span class="sc">%&gt;%</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_count =</span> <span class="fu">mean</span>(tot_rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_count =</span> <span class="fu">median</span>(tot_rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_count =</span> <span class="fu">sd</span>(tot_rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>season_summaryNew</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  seasons mean_count median_count sd_count     n
  &lt;fct&gt;        &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
1 Autumn      22099.       23350     6711.    81
2 Spring      17910.       17590     8357.    90
3 Summer      24818.       25572.    7297.    92
4 Winter       5413.        5498     1808.    90</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bike rental by Holiday</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>holiday_summaryNew <span class="ot">&lt;-</span> sumry <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(holiday) <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_count =</span> <span class="fu">mean</span>(tot_rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_count =</span> <span class="fu">median</span>(tot_rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_count =</span> <span class="fu">sd</span>(tot_rented_bike_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>holiday_summaryNew</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  holiday    mean_count median_count sd_count     n
  &lt;fct&gt;           &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
1 Holiday        12700.        7184    10504.    17
2 No Holiday     17727.       19104.    9862.   336</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#A quick visualization </span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sumry, <span class="fu">aes</span>(<span class="at">x =</span> seasons, <span class="at">y =</span> tot_rented_bike_count, <span class="at">fill =</span> seasons)) <span class="sc">+</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Total Bike Rental by Season (Functioning Days Only)"</span>,</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Season"</span>, <span class="at">y =</span> <span class="st">"Total Rented Bike"</span>) <span class="sc">+</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework8_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation between numeric variables</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>num_vars <span class="ot">&lt;-</span> sumry <span class="sc">|&gt;</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()<span class="sc">|&gt;</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric))</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">str</span>(num_vars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [353 × 9] (S3: tbl_df/tbl/data.frame)
 $ tot_rented_bike_count     : num [1:353] 9539 8523 7222 8729 8307 ...
 $ tot_rainfall              : num [1:353] 0 0 4 0.1 0 1.3 0 0 0 4.1 ...
 $ tot_snowfall              : num [1:353] 0 0 0 0 0 8.6 10.4 0 0 32.5 ...
 $ mean_temperature          : num [1:353] -2.454 1.325 4.875 -0.304 -4.458 ...
 $ mean_humidity             : num [1:353] 45.9 62 81.5 52.5 36.4 ...
 $ mean_wind_speed           : num [1:353] 1.54 1.71 1.61 3.45 1.11 ...
 $ mean_visibility           : num [1:353] 1871 1471 456 1363 1959 ...
 $ mean_dew_point_temperature: num [1:353] -13.55 -5.72 1.88 -9.93 -17.43 ...
 $ mean_solar_radiation      : num [1:353] 0.2487 0.2637 0.1254 0.2829 0.0358 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute correlation matrix</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">cor</span>(num_vars, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>), <span class="dv">2</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Melt for ggplot</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>cor_long <span class="ot">&lt;-</span> <span class="fu">melt</span>(cor_matrix)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot heatmap (0 to 1 scale)</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cor_long, <span class="fu">aes</span>(Var1, Var2, <span class="at">fill =</span> value)) <span class="sc">+</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(value, <span class="dv">2</span>)), <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradientn</span>(</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">colours =</span> <span class="fu">c</span>(<span class="st">"white"</span>, <span class="st">"yellow"</span>, <span class="st">"orange"</span>, <span class="st">"red"</span>, <span class="st">"darkred"</span>),</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits  =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">name    =</span> <span class="st">"Correlation"</span></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Heatmap of Positive Correlations (0–1)"</span>,</span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework8_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the box plot above, we can see clearly see that the total Bike rented is highest during summer and lowest during winter. It is good to note that, mean temperature has strong positive correlation with bike rental activity with r=0.75 suggesting higher temperature correspond to higher bike rental. you can see similar relation with variable dew point temperature and solar radiation as both accompany high temperature.</p>
</section>
<section id="split-the-data" class="level1">
<h1>Split the Data</h1>
<p>Now we are ready to split our data into training and test</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix the random numbers by setting the seed </span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This enables the analysis to be reproducible </span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1216</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Put 3/4 of the data into the training set </span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>Bike_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(sumry, <span class="at">prop =</span> <span class="dv">3</span><span class="sc">/</span><span class="dv">4</span>, <span class="at">strata =</span> seasons)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create data frames for the two sets:</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>train_bike <span class="ot">&lt;-</span> <span class="fu">training</span>(Bike_split)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>test_bike  <span class="ot">&lt;-</span> <span class="fu">testing</span>(Bike_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>we have 90 observation in the test dataset and 263 in the training dataset.</p>
<p>we performed ten-fold cross validation on the training dataset.We kept the stratification so that each fold maintain the same seasonal distribution as the full dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1216</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>trainCV <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  train_bike,</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">v =</span> <span class="dv">10</span>,          <span class="co"># number of folds</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">strata =</span> seasons <span class="co"># keep stratification consistent</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>trainCV</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#  10-fold cross-validation using stratification 
# A tibble: 10 × 2
   splits           id    
   &lt;list&gt;           &lt;chr&gt; 
 1 &lt;split [236/27]&gt; Fold01
 2 &lt;split [236/27]&gt; Fold02
 3 &lt;split [236/27]&gt; Fold03
 4 &lt;split [236/27]&gt; Fold04
 5 &lt;split [236/27]&gt; Fold05
 6 &lt;split [236/27]&gt; Fold06
 7 &lt;split [236/27]&gt; Fold07
 8 &lt;split [238/25]&gt; Fold08
 9 &lt;split [238/25]&gt; Fold09
10 &lt;split [239/24]&gt; Fold10</code></pre>
</div>
</div>
</section>
<section id="fitting-mlr-models" class="level1">
<h1>Fitting MLR Models</h1>
<p>Below, we created a recipe using the training dataset,indicating,tot_rented_bike_count as a response variable and all the rest as predictor variables excluding date.</p>
<section id="first-recipe" class="level2">
<h2 class="anchored" data-anchor-id="first-recipe">First recipe</h2>
<p>In the first recipe, we created, a new factor variable representing weekday vs weekend then the date and the intermediate variable creating this factor variable was removed, numeric variables were standardized (Center and scale). Dummy variables were also generated for the seasons, holiday and the newly created factor variable. data was then prepared with prep() and the transformations were applied using bake() prior to modeling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#1st recipes</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1) Use Date to get day-of-week, but drop the original Date from predictors</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    This will create a column like "Date_dow"</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>bike_rec_1 <span class="ot">&lt;-</span> <span class="fu">recipe</span>(tot_rented_bike_count <span class="sc">~</span> ., <span class="at">data =</span> train_bike) <span class="sc">%&gt;%</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  recipes<span class="sc">::</span><span class="fu">step_date</span>(date,<span class="at">features =</span> <span class="st">"dow"</span>, <span class="at">keep_original_cols =</span> <span class="cn">FALSE</span> ) <span class="sc">%&gt;%</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2) Create weekday/weekend factor from the day-of-week variable</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    (Date_dow is an ordered factor from Sun, Mon, ..., Sat)</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">day_type =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>      date_dow <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sat"</span>, <span class="st">"Sun"</span>),</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>      <span class="st">"weekend"</span>,</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>      <span class="st">"weekday"</span></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3) Remove the intermediate day-of-week,created by step_date().  </span></span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(date_dow) <span class="sc">%&gt;%</span></span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 4) Standardize (center &amp; scale) all numeric predictors</span></span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 5) Create dummy variables for all nominal predictors (Seasons, Holiday, day_type, etc.)</span></span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>())</span>
<span id="cb53-27"><a href="#cb53-27" aria-hidden="true" tabindex="-1"></a>bike_rec_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Recipe ──────────────────────────────────────────────────────────────────────</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Inputs </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Number of variables by role</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>outcome:    1
predictor: 11</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Operations </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Date features from: date</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Variable mutation for: factor(if_else(date_dow %in% c("Sat", "Sun"),
  "weekend", "weekday"))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Variables removed: date_dow</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Centering and scaling for: all_numeric_predictors()</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Dummy variables from: all_nominal_predictors()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>bike_prep_1 <span class="ot">&lt;-</span> <span class="fu">prep</span>(bike_rec_1)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>baked_train <span class="ot">&lt;-</span> <span class="fu">bake</span>(bike_prep_1, <span class="at">new_data =</span> <span class="cn">NULL</span>)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(baked_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 263
Columns: 14
$ tot_rainfall               &lt;dbl&gt; -0.31060435, 2.48974199, -0.31060435, -0.31…
$ tot_snowfall               &lt;dbl&gt; -0.2261843, -0.2261843, -0.2261843, -0.2261…
$ mean_temperature           &lt;dbl&gt; 1.075165580, 0.915833776, 0.885689921, 0.93…
$ mean_humidity              &lt;dbl&gt; 0.16024055, 1.57056867, 0.85842279, 0.19933…
$ mean_wind_speed            &lt;dbl&gt; -0.85650959, -1.11443791, 0.83844794, 1.435…
$ mean_visibility            &lt;dbl&gt; 0.85841057, 0.17765465, 0.07738893, 1.09250…
$ mean_dew_point_temperature &lt;dbl&gt; 0.97529819, 1.24576766, 1.00796358, 0.87468…
$ mean_solar_radiation       &lt;dbl&gt; 0.98196617, -1.31170000, 1.06383641, 1.1703…
$ tot_rented_bike_count      &lt;dbl&gt; 26010, 10802, 29529, 31114, 30381, 29813, 3…
$ seasons_Spring             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ seasons_Summer             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ seasons_Winter             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ holiday_No.Holiday         &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0…
$ day_type_weekend           &lt;dbl&gt; 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0…</code></pre>
</div>
</div>
</section>
<section id="second-recipe" class="level2">
<h2 class="anchored" data-anchor-id="second-recipe">Second recipe</h2>
<p>For the second recipe we did the same thing as the first recipe, in addition, interaction terms were created between selected variables to allow the model to capture combined effects. The recipe was prepared using prep() and applied to the dataset using bake() prior to modeling.”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co">#2nd recipes</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1) Use Date to get day-of-week, but drop the original Date from predictors</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    This will create a column like "Date_dow"</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>bike_rec_2 <span class="ot">&lt;-</span> <span class="fu">recipe</span>(tot_rented_bike_count <span class="sc">~</span> ., <span class="at">data =</span> train_bike) <span class="sc">%&gt;%</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  recipes<span class="sc">::</span><span class="fu">step_date</span>(date,<span class="at">features =</span> <span class="st">"dow"</span>, <span class="at">keep_original_cols =</span> <span class="cn">FALSE</span> ) <span class="sc">%&gt;%</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2) Create weekday/weekend factor from the day-of-week variable</span></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    (Date_dow is an ordered factor from Sun, Mon, ..., Sat)</span></span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(</span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">day_type =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(</span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>      date_dow <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sat"</span>, <span class="st">"Sun"</span>),</span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a>      <span class="st">"weekend"</span>,</span>
<span id="cb69-14"><a href="#cb69-14" aria-hidden="true" tabindex="-1"></a>      <span class="st">"weekday"</span></span>
<span id="cb69-15"><a href="#cb69-15" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb69-16"><a href="#cb69-16" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb69-17"><a href="#cb69-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb69-18"><a href="#cb69-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb69-19"><a href="#cb69-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3) Remove the intermediate day-of-week variable created by step_date()</span></span>
<span id="cb69-20"><a href="#cb69-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(date_dow) <span class="sc">%&gt;%</span></span>
<span id="cb69-21"><a href="#cb69-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb69-22"><a href="#cb69-22" aria-hidden="true" tabindex="-1"></a>   <span class="co"># 5) Create dummy variables for all nominal predictors (Seasons, Holiday, day_type, etc.)</span></span>
<span id="cb69-23"><a href="#cb69-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>(),<span class="at">keep_original_cols =</span> <span class="cn">FALSE</span>)<span class="sc">%&gt;%</span></span>
<span id="cb69-24"><a href="#cb69-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-25"><a href="#cb69-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add interaction terms:</span></span>
<span id="cb69-26"><a href="#cb69-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. seasons * holiday</span></span>
<span id="cb69-27"><a href="#cb69-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. seasons * temp</span></span>
<span id="cb69-28"><a href="#cb69-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. temp * rainfall</span></span>
<span id="cb69-29"><a href="#cb69-29" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_interact</span>(</span>
<span id="cb69-30"><a href="#cb69-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Use selector functions directly with the colon operator, no parentheses</span></span>
<span id="cb69-31"><a href="#cb69-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">terms =</span> <span class="sc">~</span> <span class="fu">starts_with</span>(<span class="st">"seasons_"</span>)<span class="sc">:</span>holiday_No.Holiday <span class="sc">+</span></span>
<span id="cb69-32"><a href="#cb69-32" aria-hidden="true" tabindex="-1"></a>              <span class="er">~</span> <span class="fu">starts_with</span>(<span class="st">"seasons_"</span>)<span class="sc">:</span>mean_temperature <span class="sc">+</span></span>
<span id="cb69-33"><a href="#cb69-33" aria-hidden="true" tabindex="-1"></a>              mean_temperature<span class="sc">:</span>tot_rainfall</span>
<span id="cb69-34"><a href="#cb69-34" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb69-35"><a href="#cb69-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-36"><a href="#cb69-36" aria-hidden="true" tabindex="-1"></a> <span class="co"># 4) Standardize (center &amp; scale) all numeric predictors</span></span>
<span id="cb69-37"><a href="#cb69-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>()) </span>
<span id="cb69-38"><a href="#cb69-38" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb69-39"><a href="#cb69-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-40"><a href="#cb69-40" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb69-41"><a href="#cb69-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-42"><a href="#cb69-42" aria-hidden="true" tabindex="-1"></a>bike_rec_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Recipe ──────────────────────────────────────────────────────────────────────</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Inputs </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Number of variables by role</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>outcome:    1
predictor: 11</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Operations </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Date features from: date</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Variable mutation for: factor(if_else(date_dow %in% c("Sat", "Sun"),
  "weekend", "weekday"))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Variables removed: date_dow</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Dummy variables from: all_nominal_predictors()</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Interactions with: ...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Centering and scaling for: all_numeric_predictors()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>bike_prep_2 <span class="ot">&lt;-</span> <span class="fu">prep</span>(bike_rec_2)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>baked_train2 <span class="ot">&lt;-</span> <span class="fu">bake</span>(bike_prep_2, <span class="at">new_data =</span> <span class="cn">NULL</span>)</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(baked_train2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 263
Columns: 21
$ tot_rainfall                        &lt;dbl&gt; -0.31060435, 2.48974199, -0.310604…
$ tot_snowfall                        &lt;dbl&gt; -0.2261843, -0.2261843, -0.2261843…
$ mean_temperature                    &lt;dbl&gt; 1.075165580, 0.915833776, 0.885689…
$ mean_humidity                       &lt;dbl&gt; 0.16024055, 1.57056867, 0.85842279…
$ mean_wind_speed                     &lt;dbl&gt; -0.85650959, -1.11443791, 0.838447…
$ mean_visibility                     &lt;dbl&gt; 0.85841057, 0.17765465, 0.07738893…
$ mean_dew_point_temperature          &lt;dbl&gt; 0.97529819, 1.24576766, 1.00796358…
$ mean_solar_radiation                &lt;dbl&gt; 0.98196617, -1.31170000, 1.0638364…
$ tot_rented_bike_count               &lt;dbl&gt; 26010, 10802, 29529, 31114, 30381,…
$ seasons_Spring                      &lt;dbl&gt; -0.5835555, -0.5835555, -0.5835555…
$ seasons_Summer                      &lt;dbl&gt; -0.595246, -0.595246, -0.595246, -…
$ seasons_Winter                      &lt;dbl&gt; -0.5835555, -0.5835555, -0.5835555…
$ holiday_No.Holiday                  &lt;dbl&gt; 0.2366667, 0.2366667, 0.2366667, 0…
$ day_type_weekend                    &lt;dbl&gt; 1.5656215, -0.6362954, -0.6362954,…
$ seasons_Spring_x_holiday_No.Holiday &lt;dbl&gt; -0.5718694, -0.5718694, -0.5718694…
$ seasons_Summer_x_holiday_No.Holiday &lt;dbl&gt; -0.5835555, -0.5835555, -0.5835555…
$ seasons_Winter_x_holiday_No.Holiday &lt;dbl&gt; -0.5426257, -0.5426257, -0.5426257…
$ seasons_Spring_x_mean_temperature   &lt;dbl&gt; -0.5290056, -0.5290056, -0.5290056…
$ seasons_Summer_x_mean_temperature   &lt;dbl&gt; -0.5879746, -0.5879746, -0.5879746…
$ seasons_Winter_x_mean_temperature   &lt;dbl&gt; 0.2362109, 0.2362109, 0.2362109, 0…
$ mean_temperature_x_tot_rainfall     &lt;dbl&gt; -0.27156936, 2.90166999, -0.271569…</code></pre>
</div>
</div>
</section>
<section id="third-recipe" class="level2">
<h2 class="anchored" data-anchor-id="third-recipe">Third recipe</h2>
<p>For the third recipe, in addition to the second recipe, quadratic terms were created for numeric predictors to capture potential nonlinear relationships. The recipe was prepared using prep() and applied to the dataset using bake() prior to modeling.”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co">#3rd recipes</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1) Use Date to get day-of-week, but drop the original Date from predictors</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    This will create a column like "Date_dow"</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>bike_rec_3 <span class="ot">&lt;-</span> <span class="fu">recipe</span>(tot_rented_bike_count <span class="sc">~</span> ., <span class="at">data =</span> train_bike) <span class="sc">%&gt;%</span></span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>  recipes<span class="sc">::</span><span class="fu">step_date</span>(date,<span class="at">features =</span> <span class="st">"dow"</span>, <span class="at">keep_original_cols =</span> <span class="cn">FALSE</span> ) <span class="sc">%&gt;%</span></span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2) Create weekday/weekend factor from the day-of-week variable</span></span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    (Date_dow is an ordered factor from Sun, Mon, ..., Sat)</span></span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(</span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">day_type =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(</span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>      date_dow <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sat"</span>, <span class="st">"Sun"</span>),</span>
<span id="cb86-13"><a href="#cb86-13" aria-hidden="true" tabindex="-1"></a>      <span class="st">"weekend"</span>,</span>
<span id="cb86-14"><a href="#cb86-14" aria-hidden="true" tabindex="-1"></a>      <span class="st">"weekday"</span></span>
<span id="cb86-15"><a href="#cb86-15" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb86-16"><a href="#cb86-16" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb86-17"><a href="#cb86-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb86-18"><a href="#cb86-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-19"><a href="#cb86-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3) Remove the intermediate day-of-week variable created by step_date()</span></span>
<span id="cb86-20"><a href="#cb86-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(date_dow) <span class="sc">%&gt;%</span></span>
<span id="cb86-21"><a href="#cb86-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-22"><a href="#cb86-22" aria-hidden="true" tabindex="-1"></a>   <span class="co"># 5) Create dummy variables for all nominal predictors (Seasons, Holiday, day_type, etc.)</span></span>
<span id="cb86-23"><a href="#cb86-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>(),<span class="at">keep_original_cols =</span> <span class="cn">FALSE</span>, <span class="at">one_hot =</span> <span class="cn">FALSE</span>)<span class="sc">%&gt;%</span> <span class="co"># avoid full-rank dummy issue</span></span>
<span id="cb86-24"><a href="#cb86-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-25"><a href="#cb86-25" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb86-26"><a href="#cb86-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add interaction terms:</span></span>
<span id="cb86-27"><a href="#cb86-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. seasons * holiday</span></span>
<span id="cb86-28"><a href="#cb86-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. seasons * temp</span></span>
<span id="cb86-29"><a href="#cb86-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. temp * rainfall</span></span>
<span id="cb86-30"><a href="#cb86-30" aria-hidden="true" tabindex="-1"></a> <span class="fu">step_interact</span>(</span>
<span id="cb86-31"><a href="#cb86-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Use selector functions directly with the colon operator, no parentheses</span></span>
<span id="cb86-32"><a href="#cb86-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">terms =</span> <span class="sc">~</span> <span class="fu">starts_with</span>(<span class="st">"seasons_"</span>)<span class="sc">:</span>holiday_No.Holiday <span class="sc">+</span></span>
<span id="cb86-33"><a href="#cb86-33" aria-hidden="true" tabindex="-1"></a>               <span class="er">~</span> <span class="fu">starts_with</span>(<span class="st">"seasons_"</span>)<span class="sc">:</span>mean_temperature <span class="sc">+</span></span>
<span id="cb86-34"><a href="#cb86-34" aria-hidden="true" tabindex="-1"></a>              mean_temperature<span class="sc">:</span>tot_rainfall</span>
<span id="cb86-35"><a href="#cb86-35" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb86-36"><a href="#cb86-36" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-37"><a href="#cb86-37" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 4. add quadratic terms for all numeric predictors</span></span>
<span id="cb86-38"><a href="#cb86-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_poly</span>(<span class="fu">all_numeric_predictors</span>()<span class="sc">&amp;</span> </span>
<span id="cb86-39"><a href="#cb86-39" aria-hidden="true" tabindex="-1"></a>              <span class="sc">!</span><span class="fu">starts_with</span>(<span class="st">"seasons"</span>) <span class="sc">&amp;</span> </span>
<span id="cb86-40"><a href="#cb86-40" aria-hidden="true" tabindex="-1"></a>              <span class="sc">!</span><span class="fu">starts_with</span>(<span class="st">"holiday"</span>) <span class="sc">&amp;</span></span>
<span id="cb86-41"><a href="#cb86-41" aria-hidden="true" tabindex="-1"></a>              <span class="sc">!</span><span class="fu">starts_with</span>(<span class="st">"day_type"</span>), <span class="at">degree =</span> <span class="dv">2</span>, <span class="at">options =</span> <span class="fu">list</span>(<span class="at">raw =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb86-42"><a href="#cb86-42" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-43"><a href="#cb86-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-44"><a href="#cb86-44" aria-hidden="true" tabindex="-1"></a> <span class="co"># 4) Standardize (center &amp; scale) all numeric predictors</span></span>
<span id="cb86-45"><a href="#cb86-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>()) </span>
<span id="cb86-46"><a href="#cb86-46" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-47"><a href="#cb86-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-48"><a href="#cb86-48" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-49"><a href="#cb86-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-50"><a href="#cb86-50" aria-hidden="true" tabindex="-1"></a>bike_rec_3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Recipe ──────────────────────────────────────────────────────────────────────</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Inputs </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Number of variables by role</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>outcome:    1
predictor: 11</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Operations </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Date features from: date</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Variable mutation for: factor(if_else(date_dow %in% c("Sat", "Sun"),
  "weekend", "weekday"))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Variables removed: date_dow</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Dummy variables from: all_nominal_predictors()</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Interactions with: ...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Polynomial expansion on: all_numeric_predictors() &amp; !starts_with("seasons") &amp;
  !starts_with("holiday") &amp; !starts_with("day_type")</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Centering and scaling for: all_numeric_predictors()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>bike_prep_3 <span class="ot">&lt;-</span> <span class="fu">prep</span>(bike_rec_3)</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>baked_train3 <span class="ot">&lt;-</span> <span class="fu">bake</span>(bike_prep_3, <span class="at">new_data =</span> <span class="cn">NULL</span>)</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(baked_train3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 263
Columns: 30
$ tot_rented_bike_count                  &lt;dbl&gt; 26010, 10802, 29529, 31114, 303…
$ seasons_Spring                         &lt;dbl&gt; -0.5835555, -0.5835555, -0.5835…
$ seasons_Summer                         &lt;dbl&gt; -0.595246, -0.595246, -0.595246…
$ seasons_Winter                         &lt;dbl&gt; -0.5835555, -0.5835555, -0.5835…
$ holiday_No.Holiday                     &lt;dbl&gt; 0.2366667, 0.2366667, 0.2366667…
$ day_type_weekend                       &lt;dbl&gt; 1.5656215, -0.6362954, -0.63629…
$ seasons_Spring_x_holiday_No.Holiday    &lt;dbl&gt; -0.5718694, -0.5718694, -0.5718…
$ seasons_Summer_x_holiday_No.Holiday    &lt;dbl&gt; -0.5835555, -0.5835555, -0.5835…
$ seasons_Winter_x_holiday_No.Holiday    &lt;dbl&gt; -0.5426257, -0.5426257, -0.5426…
$ seasons_Spring_x_mean_temperature      &lt;dbl&gt; -0.5290056, -0.5290056, -0.5290…
$ seasons_Summer_x_mean_temperature      &lt;dbl&gt; -0.5879746, -0.5879746, -0.5879…
$ seasons_Winter_x_mean_temperature      &lt;dbl&gt; 0.2362109, 0.2362109, 0.2362109…
$ tot_rainfall_poly_1                    &lt;dbl&gt; -0.31060435, 2.48974199, -0.310…
$ tot_rainfall_poly_2                    &lt;dbl&gt; -0.1860712, 1.1493322, -0.18607…
$ tot_snowfall_poly_1                    &lt;dbl&gt; -0.2261843, -0.2261843, -0.2261…
$ tot_snowfall_poly_2                    &lt;dbl&gt; -0.167489, -0.167489, -0.167489…
$ mean_temperature_poly_1                &lt;dbl&gt; 1.075165580, 0.915833776, 0.885…
$ mean_temperature_poly_2                &lt;dbl&gt; 1.13452210, 0.83639586, 0.78252…
$ mean_humidity_poly_1                   &lt;dbl&gt; 0.16024055, 1.57056867, 0.85842…
$ mean_humidity_poly_2                   &lt;dbl&gt; 0.03541215, 1.67491209, 0.78693…
$ mean_wind_speed_poly_1                 &lt;dbl&gt; -0.85650959, -1.11443791, 0.838…
$ mean_wind_speed_poly_2                 &lt;dbl&gt; -0.76321390, -0.90987834, 0.669…
$ mean_visibility_poly_1                 &lt;dbl&gt; 0.85841057, 0.17765465, 0.07738…
$ mean_visibility_poly_2                 &lt;dbl&gt; 0.8941104, 0.0113544, -0.103732…
$ mean_dew_point_temperature_poly_1      &lt;dbl&gt; 0.97529819, 1.24576766, 1.00796…
$ mean_dew_point_temperature_poly_2      &lt;dbl&gt; 0.5544984, 1.2655065, 0.6333100…
$ mean_solar_radiation_poly_1            &lt;dbl&gt; 0.98196617, -1.31170000, 1.0638…
$ mean_solar_radiation_poly_2            &lt;dbl&gt; 0.89021421, -1.01074072, 1.0089…
$ mean_temperature_x_tot_rainfall_poly_1 &lt;dbl&gt; -0.27156936, 2.90166999, -0.271…
$ mean_temperature_x_tot_rainfall_poly_2 &lt;dbl&gt; -0.1595040, 1.3416138, -0.15950…</code></pre>
</div>
</div>
</section>
<section id="set-up-lm" class="level2">
<h2 class="anchored" data-anchor-id="set-up-lm">Set up LM</h2>
<p>Here, we set up the linear model with linear_reg and ‘lm’ engine which fits the model by finding the line that best fits the data by minimzing squared errors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>bike_lm <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>,<span class="at">rankdeficient =</span> <span class="st">"NA"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"regression"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>workflow to integrate the pre-processing recipe with the linear regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>bike_wf1 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(bike_rec_1) <span class="sc">%&gt;%</span></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(bike_lm)  </span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>bike_wf2 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(bike_rec_2) <span class="sc">%&gt;%</span></span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(bike_lm)  </span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-9"><a href="#cb105-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-10"><a href="#cb105-10" aria-hidden="true" tabindex="-1"></a>bike_wf3 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb105-11"><a href="#cb105-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(bike_rec_3) <span class="sc">%&gt;%</span></span>
<span id="cb105-12"><a href="#cb105-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(bike_lm)   </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To select the best model, each of the workflow was trained and evaluated using 10-fold cross-validation. The fit_resamples() function was applied to each fold, and the resulting training set cross-validated errors were compared to identify the workflow with the lowest RMSE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>res1 <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(bike_wf1, <span class="at">resamples =</span> trainCV, <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse, rsq),</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">control =</span> <span class="fu">control_resamples</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>))</span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>res2 <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(bike_wf2, <span class="at">resamples =</span> trainCV, <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse, rsq),</span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">control =</span> <span class="fu">control_resamples</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>))</span>
<span id="cb106-5"><a href="#cb106-5" aria-hidden="true" tabindex="-1"></a>res3 <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(bike_wf3, <span class="at">resamples =</span> trainCV, <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse, rsq),</span>
<span id="cb106-6"><a href="#cb106-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">control =</span> <span class="fu">control_resamples</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>))</span>
<span id="cb106-7"><a href="#cb106-7" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(res1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  .metric .estimator     mean     n  std_err .config        
  &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard   4022.       10 136.     pre0_mod0_post0
2 rsq     standard      0.837    10   0.0123 pre0_mod0_post0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(res2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  .metric .estimator     mean     n  std_err .config        
  &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard   3125.       10 197.     pre0_mod0_post0
2 rsq     standard      0.901    10   0.0148 pre0_mod0_post0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(res3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  .metric .estimator     mean     n  std_err .config        
  &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard   3021.       10 200.     pre0_mod0_post0
2 rsq     standard      0.905    10   0.0158 pre0_mod0_post0</code></pre>
</div>
</div>
<p>combined all the metrices, added a column model and filtered it by rmse. Recipe 3 has the lowest RSME hence the best model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(</span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>(res1) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"recipe1"</span>),</span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>(res2) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"recipe2"</span>),</span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>(res3) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"recipe3"</span>)</span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.metric <span class="sc">==</span> <span class="st">"rmse"</span>) <span class="sc">%&gt;%</span>  <span class="co"># compare based on RMSE</span></span>
<span id="cb112-7"><a href="#cb112-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  .metric .estimator  mean     n std_err .config         model  
  &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;           &lt;chr&gt;  
1 rmse    standard   3021.    10    200. pre0_mod0_post0 recipe3
2 rmse    standard   3125.    10    197. pre0_mod0_post0 recipe2
3 rmse    standard   4022.    10    136. pre0_mod0_post0 recipe1</code></pre>
</div>
</div>
<p>we then fit the best model to the entire training dataset and computed RMSE</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>best_wf <span class="ot">&lt;-</span> bike_wf3</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>final_fit <span class="ot">&lt;-</span> <span class="fu">last_fit</span>(best_wf, <span class="at">split =</span> Bike_split, <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse))</span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(final_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  .metric .estimator .estimate .config        
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard       3003. pre0_mod0_post0</code></pre>
</div>
</div>
<p>Finally, we Obtained coefficient table using extract_fit_parsnip()and tidy().</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>final_model <span class="ot">&lt;-</span> <span class="fu">extract_fit_parsnip</span>(final_fit)</span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(final_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 5
   term                                estimate std.error statistic   p.value
   &lt;chr&gt;                                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)                           17450.      169.   103.    2.11e-196
 2 seasons_Spring                        -3923.     1363.    -2.88  4.36e-  3
 3 seasons_Summer                        13374.     2292.     5.84  1.78e-  8
 4 seasons_Winter                        -1579.     1102.    -1.43  1.53e-  1
 5 holiday_No.Holiday                      900.      376.     2.40  1.74e-  2
 6 day_type_weekend                       -927.      175.    -5.31  2.61e-  7
 7 seasons_Spring_x_holiday_No.Holiday    -282.     1183.    -0.239 8.12e-  1
 8 seasons_Summer_x_holiday_No.Holiday    -285.     1132.    -0.251 8.02e-  1
 9 seasons_Winter_x_holiday_No.Holiday    -540.      854.    -0.633 5.28e-  1
10 seasons_Spring_x_mean_temperature      2582.      625.     4.13  5.04e-  5
# ℹ 20 more rows</code></pre>
</div>
</div>
<p>From the final model we can interpret the coefficient for seasons_Spring as bike rental in spring is predicted to be ~3923 fewer than autumn, our reference season.Summer is predicted to have ~13373 more bike rental compared to autumn. Weekends are predicted to have 927 fewer bike rentals than week days which is our reference group.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>